version: '3.4'
services:
  # Used for dev testing and integration testing
  app:
    build:
      context: .
    command: sleep infinity
    environment:
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_API_URL: ${RESEND_API_URL} # defaults value https://api.resend.com
    volumes:
      - .:/app